# Welcome to Jekyll!

# Website settings
title: "Bhaskar Mitra"
description: "Bhaskar's blog."
keywords: "Bhaskar,Mitra,Microsoft,Information,Retrieval,Neural,Networks"
baseurl: "/"
url: "https://bmitra-msft.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Bhaskar'
  first_name: 'Bhaskar'
  last_name: 'Mitra'
  email: 'bmitra@microsoft.com'
  facebook_username: 'UnderdogGeek'
  twitter_username: 'UnderdogGeek'
  github_username: 'bmitra-msft'
  head_img: 'static/img/landing/bmitra-clipper.jpg'
  desc: 'I am a senior applied scientist at Bing in Microsoft Cambridge. Also, currently pursuing a (part-time) doctorate at University College London. My research interests include representation learning and neural networks, and in particular their application to modern day information retrieval.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'research'
    i18n: 'nav.research'
    name: 'Research'
    tpl: 'research.html'
    css: 'navy-section'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'navy-section'

  - id: 'sail4timmy'
    i18n: 'nav.sail4timmy'
    name: '#sail4timmy'
    tpl: 'sail4timmy.html'
    css: 'testimonials navy-section'

# blog img path
img_path: 'static/img/blog'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
